### ISSUE TITLE
ModalRoot, как новый слой навигации

### ISSUE THREAD

**Issue by egorprnn** [YerinAlexey/vkui-navigation#5]
В данный момент VKUI имеет несколько вариантов навигации:
`Root` - `View` - `Panel`
`Epic` - `View` - `Panel`

`Root` и `View` принимают prop modal, который должен содержать [`ModalRoot`](https://vkcom.github.io/vkui-styleguide/#modalroot).

Предлагаю создать новый слой навигации в библиотеке, а также методы навигации между модальными окнами.

## Логика
Можно не передавать сам ModalRoot в prop `Root`/`View`, а генерировать его прямо в этих компонентах (тогда придется добавить `View` в библиотеку отдельным компонентом), при этом разработчик сможет передавать просто массив с модальными страницами (похожая логика реализована в Tabbar):

```jsx

const Modal1 = () => {
   <ModalPage></ModalPage>
};

const Modal2 = () => {
   <ModalCard></ModalCard>
};

<View modals={[
   <Modal1 title="Настройки"/>,
   <Modal2/>
   <Modal3 title="Редактирование" onClose={() => Кастомная логика закрытия именно этого модального окна ... navigator.closeModals()}/>,
   ...
]}>
```
## TODO
- [ ] Сохранение текущей истории модальных окон. (через одно модальное окно мы можем попасть на другое)
- [ ] Метод для открытия модального окна с передачей параметров.
- [ ] Метод для закрытия модальных окон/модального окна. (обнуление текущего активного модального окна и очистка истории)
- [ ] Закрытие модальных окон при любом перемещении между панелями.
- [ ] Автоматическая генерация props onClose для ModalRoot.
~~Автоматическая генерация ModalPageHeader основываясь на props title у передаваемого элемента.~~

**Comment by YerinAlexey** [comment]
> ```js-jsx
> <View modals={[
>    <Modal1 title="Настройки"/>,
>    <Modal2/>
>    <Modal3 title="Редактирование" onClose={() => Кастомная логика закрытия именно этого модального окна ... navigator.closeModals()}/>,
>    ...
> ]}>
> ```

Я предлагаю использовать объекты (как в `Epic`). Метод выше хорош для JavaScript, но для TypeScript он не сработает

**Comment by egorprnn** [comment]
Можно и объекты, тоже вполне хороший вариант

**Comment by YerinAlexey** [comment]
@MrZillaGold к сожалению, поддержку модальных окон придется отложить. Требуется полная реконструкция роутера

**Comment by YerinAlexey** [comment]
Я сейчас не очень хочу работать с vkui-navigation и экосистемой ВК в общем. Возможно когда-то поддержка модальных окон и появится, но явно не в ближайшее время.
