### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by YerinAlexey** [YerinAlexey/vkui-navigation#7]
Вот vkui-navigation и приближается к стабилизации. К концу октября я планирую выпустить версию 1.0. 

### Зачем issue?
Здесь будут обсуждаться вопросы, связанные с API и новыми функциями. Если нужно обратиться ко мне лично, пишите в [Matrix](https://matrix.to/#/@yerinalexey:matrix.org). Отчёты об ошибках **оставляйте отдельно**. 

### Roadmap
- [ ] Поддержка модальных окон (#5)
- [ ] Рефактор. Нужно разделить типы.
- [ ] Стабилизировать API
- [ ] Приложение-песочница. Будет полезна для демонстрации, а также как платформа для отлова багов.
- [ ] Улучшить документацию. Сделать код менее специфичным, описать сигнатуры функций.
